#+HUGO_BASE_DIR: ..
#+HUGO_SECTION: post
#+HUGO_CODE_FENCE: t

#+TITLE: Technobabble
#+SUBTITLE: Ramblings of a programmer
#+TAGS: { tech(t) emacs(e) lisp clojure peopleware nostalgia }
#+TAGS: { linux society advice defective }

* About your host
  :PROPERTIES:
  :EXPORT_FILE_NAME: about
  :EXPORT_HUGO_SECTION: /
  :END:

Welcome!  My name is /Alain Picard/!

These are the 
ramblings of a curmudgeonly programmer.  I like =emacs=, lispy languages,
=Unix™=, and intelligent discussion.  I'll be talking about all those
things, and then some.  Feel free to reach out via email, or by 
leaving a comment.


* Posts
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: post
  :END:

** Welcome to my corner of the internet!
:PROPERTIES:
:EXPORT_FILE_NAME: welcome-message
:EXPORT_DATE: <2020-08-05 Wed>
:END:

*Welcome!* 

It is odd that I have been online for so long (since 1986 or so)
but have never felt the need to publish content (apart from the occasional
piece of open source software, here and there).  There was one early
attempt, in hand-crafted HTML, around 1994, that I might try to resurrect
for posterity... but nothing since.

What changed?  I guess with the passage of time, my work took
me from being a "producer" to being more of a "mentor".  During my
career I began to notice the same problems, (and often, the same wrong
solutions) over and over, so I figured I might as well write down
some of my thoughts on these matters (not that I expect any to care
what /I/ think!)

Who am I?  A /defrocked astronomer/[fn:1], then a programmer[fn:2] in Australia,
where I still reside.  
A /rationalist/ because the only way we seem to have figured out things
which are actually true, without lying to ourselves, is the scientific 
method.
A /curmudgeon/, certainly, having been told at
the tender age of 17 by my favourite maths professor, no less, that I
had already achieved the cynicism of a 75 year old.  They call it pessimism;
I call it /being a realist/.  Never stopped me from being happy...


I now work as a consultant, principally (but not
exclusively) for small companies using [[https://clojure.org][clojure]].  



**** Notes

[fn:1] I obtained my Ph.D. from [[https://www.astro.caltech.edu/department/grad_alumni.html][Caltech in 1991]], in Cosmology, and worked 
for a few years at [[https://www.esa.int/About_Us/ESTEC][the European Space Observatory]].

[fn:2] Although I worked at many places, the work I am most proud of
was performed at [[https://newsroom.accenture.com/industries/communications/accenture-to-acquire-maxamine-and-memetrics-expanding-digital-marketing-sciences-services.htm][Memetrics]], a now defunct company acquired by Accenture in 2008.
 

** TODO Authoring this blog                                        :tech:emacs:
:PROPERTIES:
:EXPORT_FILE_NAME: authoring-this-blog
:EXPORT_DATE: <2020-08-06 Thu>
:END:

I use =Hugo= with the =Academic= theme, within =emacs= using =ox-hugo=.

** My life in emacs                               :emacs:advice:nostalgia:tech:
:PROPERTIES:
:EXPORT_FILE_NAME: life-in-emacs
:EXPORT_DATE: <2020-08-11 Tue>
:END:


*** In the beginning...

I've been using [[https://www.gnu.org/software/emacs/][GNU Emacs]] pretty much daily since 1991, when I got
kicked off /deimos/, a VAX-780 in the astronomy department at Caltech.
Well, I didn't just get kicked off of it... it stopped existing, as
vaxen fell out of fashion for being cost ineffective, and the department
made the transition to a Convex, a now defunct super minicomputer.  But 
that's a story for another day.

Finding myself with a brand new Sun Sparcstation, I then had to find
another editor (at the time, I was a wiz on VMS's =EDT= editor) to write
my thesis, the manuscript of which was going to be written in TeX.  My
choices seemed to be =vi= and =emacs=, as even then I (correctly) intuited
that sticking with an emulator for a defunct system was probably not a
good long term strategy.

Emacs had this nice mode called [[https://www.gnu.org/software/auctex/][AUCTeX]] to facilitate
authoring [[http://www.tug.org/][TeX]] documents.  I took the plunge, and have never looked back.
I of course totally fell for the tinkerer's malady which affects most
new emacs users, and spent more time exploring and configuring emacs
that writing my thesis (standard work avoidance tactics).

As I think back about my career in programming, it seems odd that such
an... /accidental/ choice ended up having such a deep impact on me.  Later,
I would come to appreciate emacs as a "programmable editor", learn lisp,
and eventually even build a company's technological core on [[https://common-lisp.net/][Common Lisp]];
I'm quite that would never have happened had I not had my eyes opened to
the existence of such deeply interactive and evolveable systems.

*** Happy, productive years go by

The next two decades saw me /living/ in emacs.  From version 18.57,
emacs rapidly developed into an actual GUI application (whoa!  modern!)
with the 19.X release.  Then we were off the the races.
Working in =C++=, then =lisp=,
reading/writing mail and usenet (using =VM= and, later, [[http://www.gnus.org/][GNUS]]), various
folding modes (until the category killer, [[https://orgmode.org/][org-mode]] appeared in 2003),
version control (first with SVN, then [[https://www.mercurial-scm.org/][mercurial]], and, finally the
most wondrous [[https://magit.vc/][magit]], which rescues the horrible =git= from the pathetic
mess that is its UI); emacs gave me loyal service during countless
hours.  

Cryptography, programming, editing remote files, diffing, rectangle
modes... my motto became "The Answer is Emacs.  Now, what was the
question?"  Even better, as computers got faster, emacs' reputation
for being slow and resource hungry began to fade, and now this appears
quaint, as single purpose applications like =slack=, a glorified IRC
system, dwarf emacs in terms of resource usage.

Startup time?  Not a problem if you never leave it; this
session is shorter than most...  I remember getting to over
a year of uptime once.
#+begin_src emacs-lisp
(emacs-uptime)
"23 days, 7 hours, 41 minutes, 24 seconds"
#+end_src
I'm guessing I had to reboot my computer for some reason...

*** Teaching emacs

I guess I sort of ended being the emacs guru and evangelist wherever
I went, so I ended up teaching emacs to quite a few people.  I discovered
an interesting phenomenon: many people took to emacs quite enthusiastically,
but usually for different reasons!  It seems emacs has many faces, and
people need to discover their own "killer app" to see the light.

Of course, today, many, many more special purpose tools and IDEs exist
which provide much of this functionality straight out of the box
(often better), it is difficult to justify the emacs way.  Add to this
that the emacs terminology is antiquated (a "window" in emacs doesn't mean
what you think, you want a "frame", you don't "cut and paste" in emacs,
you "kill and yank") it must feel like an alien and stubbornly archaic land
to a new user.  So why should they persevere?

*** By their /tools/ shall ye know them

/Expert/ tools are not designed like tools for beginners.  I watch 
my younger colleagues, and many seem to be stuck in a form of arrested
development, paralyzed in a sort of "eternal beginner" state.  I think
it has to do with the idea of "user friendliness", which got (mis-)interpreted
as "beginner friendliness".  But a professional programmer isn't (or, at
least, shouldn't /stay)/ a beginner!  I watch them move the mouse, click,
drag, cut, scroll (again, with the mouse), click and finally paste... and
mentally calculate how long that took, how many times a day they do it,
how many days in their life they will do it for... and despair.  Not to mention
to mental interruption to the flow imposed by each of these tiny delays, each
of these additional bits of friction.

So let me be clear: I believe the young programmer should strive to make
their tool /disappear/ from their consciousness; the mechanical aspects of your
work should be as a musician playing his instrument: he thinks not of the
instrument but about the music.  The instrument "plays itself".

This is the realm in which emacs excels.  The reason for this is that it's 
more a /meta tool/ than a tool.  The opening line of the emacs manual
is essentially unchanged to this day from my hardcopy version, sixth edition, 1987:

#+begin_quote
Emacs is the extensible, customizable, self-documenting real-time
display editor.
#+end_quote

This emphasis on /extensibility/ and /customizability/ is the essence of emacs.
Emacs works the way /you/ do, not the way around.  That is why, unlike these
other "friendly" tools, it /never/ runs out of features, nor slows you down,
nor draws attention to itself.  The price you pay for this is climbing the
steep learning curve.  Did you think this was going to be easy?  Nothing
worthwhile ever is.


*** Modern times

These days I am deeply conflicted about whether or not to recommend to young
programmers that they follow this path; it's hard for me to gauge to what extent
the time I invested in learning this tool (and the rewards I got from it) are still
achievable today.  For me, the principal win has been that I could do just about
/all/ of my work from within emacs, thus compounding efficiencies as I switched
from one [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Major-Modes.html][mode]] to another.  But the world has moved on, and working outside a
browser now becomes more and more difficult.  Even tools like the
[[https://chrome.google.com/webstore/detail/edit-with-emacs/ljobjlafonikaiipfkggjbhkghgicgoh][Edit with Emacs]] chrome browser extension only help marginally, because now
developers are made to use obnoxious tools like Jira, which (on purpose, I'm sure)
[[https://www.atlassian.com/blog/archives/why-we-removed-wiki-markup-editor-in-confluence-4#comments][prevent round tripping]] of their markup language to and from plain text (/i.e./ markdown).  
Furthermore, even though I still read my mail from emacs, I have to pipe it
through the browser to properly view more than half of messages I now get.
I sure long for the days of plain ASCII email...

What advice would I give a young programmer choosing today?  I would
say you should still consider =emacs= if you are the type of person who
believes in expert tools.  Emacs is not flashy or pretty out of the
box.  Remember, think of emacs not as a finished product, but as a
/toolkit/ with which to create your own, custom work environment.  Emacs
is an /investment/: you'll have to /work/ at it.  You will either find
yourself falling down the rabbit hole, and enjoying the experience, or
totally bewildered and hating it.  Both are fine!

But if you think you'll still be doing this job in 20 years, if you want to
become ever more effective at it, if you want your work tool to become
an extension of your mind, then perhaps =emacs= /is/ for you, even now, in 2020.

You'll just have to find out for yourself, won't you?



** TODO This one uses the awesome power of Org
:PROPERTIES:
:EXPORT_FILE_NAME: power-of-org
:EXPORT_DATE: <2020-08-01 Sat>
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :math true
:END:


The question is: /who/ is doing the exporting?  I think
it's =org-hugo-auto-export-mode= in the /Local Variables/.

\( e^{i\pi} + 1 = 0 \)

 - Here we refer to [[/blog][Blog]]
 - And make a change
 - Here we refer to 
 #+begin_export html
 <a src="/">The home page</a>
 #+end_export

 - And here to an inner link on [[/blog/foo][the foo page]]
 - And highlighting is still failing.

 #+begin_src clojure 
   (defn foo
     "Do some foo"
     [x y]
     (log "Some foobar message")
     (+ x y))
 #+end_src

#+hugo: more

#+begin_src lisp :hl_lines 2 -n 20
  (message "This is line 1")
  (message "This is line 2")
  (message "This is line 3")
#+end_src

*** Equations:

LaTeX formatted equation: \( E = -J \sum_{i=1}^N s_i s_{i+1} \)

*** Another one

\begin{equation}
\label{eq:1}
C = W\log_{2} (1+\mathrm{SNR})
\end{equation}

And that's /all/, folks!


***  Weight

#+attr_html: :class striped--light-gray
| Date                   | Weight (kg) | Notes                     |
|------------------------+-------------+---------------------------|
| <2009-10-14 Wed>       |        72.4 |                           |
| <2009-10-15 Thu>       |        72.6 |                           |
| <2009-10-17 Sat>       |        72.8 |                           |
| <2009-10-18 Sun>       |        72.8 |                           |
| <2009-10-19 Mon>       |        73.4 | (!!)                      |
| <2009-10-20 Tue>       |        73.2 |                           |
| <2009-10-21 Wed>       |        72.8 |                           |
| <2010-04-04 Sun>       |        71.4 |                           |
| [2013-02-05 Tue]       |        73.0 | Weight Watchers, reboot   |
| [2013-02-06 Wed]       |        72.8 |                           |
| [2013-02-07 Thu]       |        74.0 |                           |
| [2013-02-14 Thu]       |        74.4 |                           |
| [2013-07-03 Wed]       |        72.4 |                           |
| [2013-12-28 Sat]       |        74.2 | Ouch.                     |
| <2016-01-06 Wed 17:33> |        75.6 |                           |
| <2017-08-29 Tue 09:14> |        77.0 | Ouch!!                    |


*** Inline styled table
#+begin_export html
<style>
.my-table th,
.my-table td {
    padding: 20px;
    text-align: left;
}
</style>
#+end_export

#+caption: Table with verbatim CSS
#+attr_html: :class my-table
| h1  | h2  | h3  |
|-----+-----+-----|
| abc | def | ghi |

 
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:

** TODO Linters are a tool...
:PROPERTIES:
:EXPORT_FILE_NAME: post-2
:EXPORT_DATE: <2020-07-30 Thu>
:END:

... not an absolute rule.

I was working at a company once...


* TODO Get snippets or templates for new blog entries
* TODO Figure out distinction between `tags' and `categories'
* TODO Get nice fonts.

I think the combination I'm liking is:
 - Libre Baskerville for body text
 - Open Sans "Light Italic" 300 weight for headings.

<link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@700&family=Alegreya:ital,wght@0,400;0,700;1,400;1,700&family=Cormorant:ital,wght@0,500;0,700;1,500;1,700&family=Goudy+Bookletter+1911&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Open+Sans:ital,wght@1,300&family=Raleway&display=swap" rel="stylesheet">


* TODO Figure out how to get Disqus comments to load

My Disqus url is
s.src = 'https://technobabble-2.disqus.com/embed.js';
* TODO Figure out how to get styling to "take"; the following doesn't work yet

Also, add .pre to be font-size 1.0rem.

.navbar-light .navbar-brand {
￼    color: #999999;
￼    font-size: 180%;
￼    color: #d58d16;
}
nav main

$navbar-brand-font-size: 1.8rem;


.navbar-light .navbar-brand {
￼    font-size: 180%;
￼    color: #d58d16;
     font-family: cursive;
}


#8fc9ff

* TODO Blogging ideas
 - [ ] Why I hate browser based interfaces
 - [ ] I miss Usenet
 - [ ] Teaching clojure
 - [ ] Software is mostly social, not technical
 - [ ] Reinventing the wheel, poorly
 - [ ] Memories of the first wiki c2.com
 - [ ] Comments on external sites I enjoyed,
   like 
   + the rationality website
   + Harry Potter fanfic
 - [ ] Really smart people: Thos who helped me at caltech without need or hope of me paying it back (Gunn, Hester)
       Now I understand why they did this; the desire to repay what was given freely.
       Some of the smartest I've met have been some of the nicest; so smart not= asshole.
 - [ ] A plea for plain text
   Jira, Markdown brokenness
 - [ ] Use Plain Text
 - [ ] IT is faddish
     (NoSQL, microservices)
 - [ ] Agile, in the beginning
 - 


